### ISSUE TITLE
Delivery Tax disappears when clicking on delivery

### ISSUE THREAD

**Issue by alexTrent123** [tastyigniter/ti-ext-cart#17]
**Expected behavior:**
**GIVEN** Tax Mode is enabled
**AND** Show Tax Breakdown in Storefront is enabled
**AND** Tax Delivery Charge
**WHEN** clicking on _"Pick-up"_ in the cart box the field _"Delivery Tax:"_ should disappear and then clicking back on "Delivery" the _"Delivery Tax:"_ field should **REAPPEAR**

**Actual behavior:**
Clicking back on delivery after clicking _"Pick-up"_ OR having the page refresh whilst _"Pick-up"_ is still selected, the _"Delivery Tax:"_ field does not appear

**Reproduce steps:**
Enable Tax Mode, Show Tax Breakdown in Storefront and Tax Delivery Charge in the admin panel
Set a delivery charge of 'x' amount when cart exceeds 'y' amount 
Load storefront and add items to basket and ensure you go over the 'y' amount to get the 'x' delivery charge
Click pick-up and then click back on delivery and the field will disappear

**Version:**
(TastyIgniter version number)

**Additional Information:**
(Additional information, if any)

**Comment by sampoyigi** [comment]
See if the commit fixes the issue, not sure if I understood the issue right.

**Comment by sampoyigi** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please reopen if it still occurs.
