### ISSUE TITLE
Cart is not detecting logged in users through "Socialite" after upgrading to Cart extension 2.3

### ISSUE THREAD

**Issue by salamaahm** [tastyigniter/ti-ext-cart#21]
**Expected behavior:**
To be able to checkout by the logged in account through "socialite"

**Actual behavior:**
Cart is still asking to login to be able to checkout

**Version:**
TastyIgniter V3.0.4beta22.4 , Cart extension 2.3

**Additional Information:**
Users created through registration are working normally

**Comment by sampoyigi** [comment]
It's not clear if this is a bug, please start a discussion on the forums or better still search the forums for existing solutions.
