### ISSUE TITLE
Misleding “Delivering to..” box & improvements for checkout page

### ISSUE THREAD

**Issue by BreakSecurity** [tastyigniter/ti-ext-cart#30]
**Expected behavior:**
During the checkout phase, the “Delivering to..” box should appear only to registered users that saved at least one address.

**Actual behavior:**
The box shown in the image appears to all customers, both those registered (without saved address) and those who are not. This is misleading for users new to the platform.

**Reproduce steps:**
Try to complete an order even if you are not registered on the site.

**Version:**
v.3.0.4-beta.23.2

**Additional Information:**
![immagine](https://user-images.githubusercontent.com/38836022/98577491-4e6e9c80-22bc-11eb-97bd-b90a7fdc55a0.png)

**Suggestion:**
Also if I have all my customer from one country (most uses cases of Tasty) city, state and some other fields can be hid from user and forced to one chosen value.

**Comment by BreakSecurity** [comment]
@sampoyigi If I open a PR to make those fields (city, address2, etc?) optional as for country would you merge?

**Comment by sampoyigi** [comment]
Sure, making those fields optional is a good idea but I can't be sure about merging until you open the PR..
