### ISSUE TITLE
Able to duplicate an order.

### ISSUE THREAD

**Issue by Tanbir17** [tastyigniter/ti-ext-cart#39]
**Expected behavior:**
On step 2 of the checkout process, when you click confirm the order is processed. (This works as intended).

**Actual behavior:**
Works as intended but if you click the 'Confirm' button at the right time you are able to duplicate the order. I have not tested to see if it will double charge on other payment methods as I tested it only with cash on delivery. You can click the Confirm button and wait for TI to process it and right before it goes to the order detail page (success page) you can see the confirm button become active for a split second. 

**Reproduce steps:**
1. Click confirm and wait for it to be highlighted again.
2. or spam click confirm.

**Version:**
Not sure about TI version but cart version is v2.5.0

**Additional Information:**
This issue previously also existed in TI V2.0 but not too sure how it was solved.

Suggestion: Once the confirm button is clicked, it is replaced by a loading icon and is unable to be clicked again.

**Comment by BreakSecurity** [comment]
Happens to me too a lot of times. I can confirm that now with the last commit on stripe gateway the withdraw happens only ONE time. But, still, it is annoying to have the system full of duplicate orders. Also even if the payment is correctly captured with STRIPE none of the orders original/duplicated will get confirmed. Is like the response from stripe get lost somehow. If you wanna more details let me know

**Comment by BreakSecurity** [comment]
How to properly test this one?

**Comment by sampoyigi** [comment]
The issue here is, there is a few millisecond gap between when the button is clicked and when the page reloads, in this gap the confirm button gets re-enabled which might lead to the user clicking the button again which in turn creates a duplicate order.. With the fix, the button doesn't get re-enabled before the page reloads, this way clicking the button while the page reloads has no effect.

**Comment by BreakSecurity** [comment]
Perfect so we can close this?

**Comment by BreakSecurity** [comment]
@sampoyigi You can close this

**Comment by Tanbir17** [comment]
Slightly the same issue. If on the checkout page you input incorrect or missing values in fields you will get the errors and the confirm box will become greyed out being unable to be clicked again. When it's available and you confirm it will take time to load the success page but will create a double order (tested in COD no other payments, so not sure if its a double charge).

Is there perhaps a way to indicate that the button is loading to the success page with maybe a loading icon?

**Comment by sampoyigi** [comment]
Fixed
