### ISSUE TITLE
Cart total at bottom is not running total

### ISSUE THREAD

**Issue by justinbriansmith** [tastyigniter/ti-ext-cart#4]
It would be nice to have the total at the bottom of a cart item builder model a running total so the user can see the item total before adding it to their cart. 

![20200509_181454](https://user-images.githubusercontent.com/65094103/81486180-085b5200-9221-11ea-9776-51595dd81172.jpg)

**Comment by sampoyigi** [comment]
Use issues to report bugs, please post your questions on the forums or better still search the forums for existing solutions.
