### ISSUE TITLE
admin.order.paymentProcessed event actions not being taken in bindCheckoutEvents

### ISSUE THREAD

**Issue by dominonin** [tastyigniter/ti-ext-cart#40]
**Expected behavior:**
When one checks out their order for pickup using Cash on Delivery as a guest, they should get an email order invoice citing what they ordered, price, etc. after the payment is marked as processed (cod is always).

**Actual behavior:**
No email is sent to customer nor restaurant/location, no matter which options are enabled under System->Settings->Setup under "Send Order Confirmation/Alert Email"

**Reproduce steps:**
Setup fresh install of TastyIgniter using Easy Setup Wizard, install demo data
Update extensions and install needed coupon extension, enable cart, frontend, local, etc., Install automation extension.
Set other needed options like currency (I used USD)
Set mail setup to use send mail with default args
Confirm that System->Settings->Setup under "Send Order Confirmation/Alert Email" is set to customer and to restaurant or just to customer
Go to order menu, choose pickup, choose any item, choose for pickup, checkout
When checkout completes and success page states order received, no email invoice is set. 

**Version:**
v3.0.4-beta.25.2

**Additional Information:**
This was attempted on two different environments with the same effect:
- cPanel rhel server w/PHP 7.4 and needed extensions
- Docker "devilbox" web dev environment with PHP 7.4 and needed extensions
No error in logs observed
No email was attempted to be sent using email catcher/deliverability logs
Changing order status sends out an email just fine, but no invoice
Changing the bindCheckoutEvents() to listen for the igniter.cart.orderStatusAdded causes expected emails to send out fine, but is not the ideal event

**Comment by sampoyigi** [comment]
Fixed here https://github.com/tastyigniter/TastyIgniter/commit/e1250302c4d22c5d0f4a23eec8e27b68c3cd83f4#diff-eabe9b39d1496ef0f6443e3f363dd4d969f3640e9ae4f0f7c308c16a03e2da1e
