### ISSUE TITLE
Tax for transaction fee is not calculated 

### ISSUE THREAD

**Issue by diverds1992** [tastyigniter/ti-ext-cart#52]
**Expected behavior:**
(Subtotal:	€29,25
Tax [9% inclusive]:	€2,42 (food and delivery fee)
Tax [21% inclusive]: € 0,09 (transaction fee)
Transaction fee:	€0,50
Total:	€29,75)

**Actual behavior:**
(Subtotal:	€29,25
Tax [9% inclusive]:	€2,42 (food and delivery fee)
Transaction fee:	€0,50
Total:	€29,75)

**Reproduce steps:**
(Just set a Transaction fee)

**Version:**
(TastyIgniter version v3.0.4-beta.27)

**Additional Information:**
(An option must be made with or without VAT. Otherwise the calculation is incorrect)

**Comment by ryanmitchell** [comment]
Sorry I missed this when it first came in.

@sampoyigi thoughts on how best to handle this? Im happy to do the legwork if you can give me an approach.

**Comment by sampoyigi** [comment]
Erm, the cart conditions are applied and calculated in the order they appear under Cart Settings.. Placing the Payment Fee cart total just before the VAT cart total should fix the issue.

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.
