### ISSUE TITLE
Validate stock qty when reached to zero

### ISSUE THREAD

**Issue by yoursantu** [tastyigniter/ti-ext-cart#53]
https://github.com/tastyigniter/ti-ext-cart/blob/c5a5fb1e0b79dd322fe91e57fcdda2e0c9da8eca/models/Menus_model.php#L33

Hi,
Currently the method outOfStock() only validates when the stock qty lover than zero.  and allows user add to cart even stock qty is equal to zero. 

please change 

        return $this->stock_qty < 0;

to this:

        return $this->stock_qty <= 0;

Thank you.

**Comment by ryanmitchell** [comment]
Hmm this wont work as things stand - we use 0 to indicate unlimited quantity.

@sampoyigi do we need to update outOfStock() and checkStock() to test if the item is being stock tracked and then apply logic... currently the logic works fine if its not stock tracked, but has issues if it is.

**Comment by sampoyigi** [comment]
@ryanmitchell, sure go for it and what's the issue when stock is tracked?

**Comment by ryanmitchell** [comment]
It depends on whether you see the stock qty and stock subtract fields as related or not. If they are, then having subtract off should mean we always have stock unless its -1.

I think I've misunderstood the original issue, and @yoursantu has entered zero when it should be -1 for no stock.

**Comment by sampoyigi** [comment]
Not related, so the restaurant can decide if they want inventory tracked by the system or if they want to update manually.. And we want to check the inventory whether it's tracked or not.

**Comment by yoursantu** [comment]
Hi,
I will make you more clear, (@ryanmitchell) We are using POS to maintain the Menu Items and stocks (Have created custom API to communicate between POS and Tastyigniter, this will automatically sync data in background). When the stock reaches to 0 in POS, In same time the cart still allow to add that items to cart, which is already out of stock!! (The cart only consider out of stock when stock -1)
So when i have changed the code to $this->stock_qty <= 0; this working properly for me.

**Comment by ryanmitchell** [comment]
Yea but that doesn’t work for everyone else! You need to upgrade you integration to set a stock level of -1 when your POS has zero stock.

**Comment by sampoyigi** [comment]
This issue looks fixed. Closing, but please reopen if it still occurs.
