### ISSUE TITLE
[Bug]: Not finish checkout, in the mobile device. It´s Showed two buttons checkout.

### ISSUE THREAD

**Issue by dataprol** [tastyigniter/ti-ext-cart#76]
### What happened?

On the line 3, the "disabled" status  concat with other status and cause fail:

> class="checkout-btn btn btn-primary {{ $locationIsClosed ? **'disabled'** : '' }} btn-block btn-lg"

Only orders on desktop pc are ok.
In my copy, i insert a space, to resolve. But, others fails occur. 
The orders can be completed, in the mobile phone. But, not show about order info status for the client.

### What did you expect to happen?

to show one button "checkout" and show the status after the finish order.

### Version

3.0.x

### What browser are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by ryanmitchell** [comment]
hmm that shouldn't be happening as there are spaces around the blade opening and closing tags. But if you're seeing it in production then it should be simple to open a pull request with the required change?

**Comment by dataprol** [comment]
In the DevTools of the browser is possible see the tags concated.

**Comment by dataprol** [comment]
yet i not discovery the cause of the other fail who not let be show about order info status after tap in the button for send the order.

**Comment by sampoyigi** [comment]
Not reproducible in the latest release. Please reopen this issue if it still occurs, with a set of reproducible steps.
